#!/bin/sh

choice="Starting"

while true; do
    choice=$(echo -e "Scan\nPair\nConnect\nDisconnect\nQuit" | rofi -dmenu -i -p " Bluetooth menu:")
    case $choice in
        Scan)
            bluetoothctl scan on &
            ;;
        Pair)
            device=$(bluetoothctl devices | rofi -dmenu -i -p " Pairing device:" | awk '{print $2}')
            bluetoothctl pair $device
            ;;
        Connect)
            device=$(bluetoothctl paired-devices | rofi -dmenu -i -p " Connecting device:" | awk '{print $2}')
            bluetoothctl connect $device
            connected=$device
            ;;
        Disconnect)
            if [ $connected != "" ]; then
                bluetoothctl disconnect $connected
            fi
            ;;
        Quit)
            exit 0
            ;;
        *)
            exit 0
            ;;
    esac
done

bluetoothctl scan off